#pragma once
#include <QObject>
namespace Server
{
enum MessageType : quint8
{
    USER_JOIN = 1,
    USER_LEFT,
    USERS_LIST,
    USERS_LIST_REQUEST,
    PUBLIC_MESSAGE,
    PRIVATE_MESSAGE,
    PRIVATE_MESSAGE_FAIL,
    AUTH_REQUEST,
    AUTH_SUCCESS,
    AUTH_FAIL,
    REGISTER_REQUEST,
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    JOIN_GROUP_REQUEST,
    JOIN_GROUP_SUCCESS,
    JOIN_GROUP_FAIL,
    LEAVE_GROUP_REQUEST,
    LEAVE_GROUP_SUCCESS,
    LEAVE_GROUP_FAIL,
    CREATE_GROUP_REQUEST,
    CREATE_GROUP_SUCCESS,
    CREATE_GROUP_FAIL
};
}
