#pragma once

enum MessageTypes
{
    USER_JOIN = 1,
    USER_LEFT,
    USERS_LIST,
    USERS_LIST_REQUEST,
    PUBLIC_MESSAGE,
    PRIVATE_MESSAGE,
    AUTH_REQUEST,
    AUTH_SUCCESS,
    AUTH_FAIL,
    JOIN_GROUP_REQUEST,
    JOIN_GROUP_SUCCESS,
    JOIN_GROUP_FAIL,
    LEFT_GROUP,
    CREATE_GROUP_REQUEST,
    CREATE_GROUP_SUCCESS,
    CREATE_GROUP_FAIL
};
